server:
  port: 8082

spring:
  application:
    name: wallet-service

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet_db
    username: riyada_user
    password: riyada_password
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Jackson Configuration
  jackson:
    time-zone: UTC
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'

# JWT Configuration (aligned with user service)
jwt:
  secret: riyada-jwt-secret-key-2024-very-secure-and-long-secret-key-for-production
  expiration: 86400000 # 24 hours in milliseconds

# User Service Configuration
user-service:
  url: http://localhost:8081
  endpoints:
    profile: /api/users/profile

# Logging Configuration
logging:
  level:
    com.riyada.walletservice: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
